controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

lucky:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
